### ISSUE TITLE
[NLZiet] Replay TV shows only the first 50 items

### ISSUE THREAD

**Issue by jbouwh** [dut-iptv/dut-iptv.github.io#25]
Replay TV, Recommended, Films and Series only shows 50 items.
An item with Next page e.g. is missing.
It would be nice to make the max number of items settable as well at the addon settings dialog.

**Comment by dut-iptv** [comment]
Should be fixed in .101

Note that:
-ReplayTV only show programs that are available at the selected date or when choosing A-Z are available on lineair TV during the last 7 days. In most cases this will mean you won't reach 50 items
-When you select All programs from the main menu you will have a much larger amount of shows because from this item all available NLziet programs are available irrespective of air date.
-Recommended, Movies etc. still only show about 75 items. The NLziet api does not return more items, even when using a very high limit when requesting the listing

**Comment by jbouwh** [comment]
Still missing a next button for replay tv and series (but I could be mistaken). The same trick could work there as well. Please check all places where more than 50 items could appear in the list.

**Comment by dut-iptv** [comment]
Thought I did. Next button only appears when more than 50 items are available. In ReplayTV there are almost never more than 50 items.

Please specify the exact menu where you believe items are missing and I will take a look

**Comment by jbouwh** [comment]
Have a look at yesterday

**Comment by dut-iptv** [comment]
Try .102

**Comment by jbouwh** [comment]
The source files and zip are missing in the repository...

**Comment by dut-iptv** [comment]
Sorry unrelated problem with build environment. 102 should be up

**Comment by jbouwh** [comment]
Fine, I will have a look this evening 👍

**Comment by jbouwh** [comment]
.102 works fine now. Thanks.  🥇
